### ISSUE TITLE
产生的Guid是0

### ISSUE THREAD

**Issue by codebdy** [jsmini/guid#3]
你好，
我在React里面调用guid()方法，返回结果是0呢：
![image](https://user-images.githubusercontent.com/18096128/105647736-ab084d80-5ee2-11eb-851e-a38745e88f1a.png)
![image](https://user-images.githubusercontent.com/18096128/105647753-bb202d00-5ee2-11eb-93bc-f3145440d7f4.png)
哪儿出问题了吗？

**Comment by yanhaijing** [comment]
没问题，默认的guid函数，就是从0,1,2,3,4 累加的
如果你希望从哪1开始，可能不能用guid函数了，自己写一个guid的util

```js
// util/guid.js
import {Guid} from '@jsminin/guid';

const g = new Guid(1) // 注意这里的1

export function guid(prefix) {
    return g.guid(prefix)
}
```

**Comment by yanhaijing** [comment]
我需要思考下，是否要把默认的改成从1开始，o(╯□╰)o

**Comment by codebdy** [comment]
> 我需要思考下，是否要把默认的改成从1开始，o(╯□╰)o

好的谢谢，具体原理我也不懂，我就是想生成一个唯一的ID。

**Comment by yanhaijing** [comment]
@rxwater 感谢使用
